# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# If you are using pnpm or other, you might need to add lock file
COPY pnpm-lock.yaml ./

RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the app
RUN npm run build

EXPOSE 3000

# Start the MCP server
CMD [ "npm", "run", "start" ]
